// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc.proto

package otlp

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("grpc.proto", fileDescriptor_bedfbfc9b54e5600) }

var fileDescriptor_bedfbfc9b54e5600 = []byte{
	// 187 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x2f, 0x2a, 0x48,
	0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xc9, 0x2f, 0xc9, 0x29, 0x90, 0xe2, 0x4b, 0xad,
	0x48, 0xce, 0x48, 0xcc, 0x4b, 0x4f, 0x85, 0x88, 0x1a, 0x79, 0x73, 0xf1, 0x86, 0xe6, 0x25, 0x16,
	0x55, 0xba, 0x56, 0x14, 0xe4, 0x17, 0x95, 0xa4, 0x16, 0x09, 0x59, 0x71, 0xb1, 0x41, 0xd8, 0x42,
	0x12, 0x7a, 0x20, 0x1d, 0x7a, 0x21, 0x45, 0x89, 0xc9, 0xa9, 0x10, 0xa1, 0xa0, 0xd4, 0xc2, 0xd2,
	0xd4, 0xe2, 0x12, 0x29, 0x11, 0x88, 0x0c, 0x4c, 0xb0, 0xb8, 0x20, 0x3f, 0xaf, 0x38, 0x55, 0x89,
	0xc1, 0x28, 0x80, 0x8b, 0x2f, 0xb8, 0xa4, 0x28, 0x35, 0x31, 0x17, 0x6e, 0x9a, 0x1d, 0xf9, 0xa6,
	0x69, 0x30, 0x1a, 0x30, 0x3a, 0x79, 0x70, 0xc9, 0x64, 0xe6, 0xeb, 0xe5, 0x17, 0xa4, 0xe6, 0x25,
	0xa7, 0xe6, 0x15, 0x97, 0x16, 0x43, 0x5c, 0xad, 0x57, 0x02, 0x32, 0x45, 0xaf, 0xcc, 0xd0, 0x89,
	0x0b, 0x6c, 0x5e, 0x00, 0x48, 0x30, 0x80, 0xf1, 0x15, 0x93, 0xa4, 0x7f, 0x41, 0x6a, 0x9e, 0x33,
	0x44, 0x25, 0x58, 0x10, 0x62, 0x9f, 0x5e, 0x98, 0x61, 0x12, 0x1b, 0x58, 0xa7, 0x31, 0x20, 0x00,
	0x00, 0xff, 0xff, 0x71, 0x13, 0x8c, 0x7c, 0x13, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UnaryExporterClient is the client API for UnaryExporter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UnaryExporterClient interface {
	// Sends a batch of telemetry data.
	Export(ctx context.Context, in *TraceExportRequest, opts ...grpc.CallOption) (*ExportResponse, error)
}

type unaryExporterClient struct {
	cc *grpc.ClientConn
}

func NewUnaryExporterClient(cc *grpc.ClientConn) UnaryExporterClient {
	return &unaryExporterClient{cc}
}

func (c *unaryExporterClient) Export(ctx context.Context, in *TraceExportRequest, opts ...grpc.CallOption) (*ExportResponse, error) {
	out := new(ExportResponse)
	err := c.cc.Invoke(ctx, "/otlp.UnaryExporter/Export", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UnaryExporterServer is the server API for UnaryExporter service.
type UnaryExporterServer interface {
	// Sends a batch of telemetry data.
	Export(context.Context, *TraceExportRequest) (*ExportResponse, error)
}

// UnimplementedUnaryExporterServer can be embedded to have forward compatible implementations.
type UnimplementedUnaryExporterServer struct {
}

func (*UnimplementedUnaryExporterServer) Export(ctx context.Context, req *TraceExportRequest) (*ExportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Export not implemented")
}

func RegisterUnaryExporterServer(s *grpc.Server, srv UnaryExporterServer) {
	s.RegisterService(&_UnaryExporter_serviceDesc, srv)
}

func _UnaryExporter_Export_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TraceExportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UnaryExporterServer).Export(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/otlp.UnaryExporter/Export",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UnaryExporterServer).Export(ctx, req.(*TraceExportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UnaryExporter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "otlp.UnaryExporter",
	HandlerType: (*UnaryExporterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Export",
			Handler:    _UnaryExporter_Export_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc.proto",
}

// StreamExporterClient is the client API for StreamExporter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StreamExporterClient interface {
	// Sends a batch of telemetry data.
	Export(ctx context.Context, opts ...grpc.CallOption) (StreamExporter_ExportClient, error)
}

type streamExporterClient struct {
	cc *grpc.ClientConn
}

func NewStreamExporterClient(cc *grpc.ClientConn) StreamExporterClient {
	return &streamExporterClient{cc}
}

func (c *streamExporterClient) Export(ctx context.Context, opts ...grpc.CallOption) (StreamExporter_ExportClient, error) {
	stream, err := c.cc.NewStream(ctx, &_StreamExporter_serviceDesc.Streams[0], "/otlp.StreamExporter/Export", opts...)
	if err != nil {
		return nil, err
	}
	x := &streamExporterExportClient{stream}
	return x, nil
}

type StreamExporter_ExportClient interface {
	Send(*TraceExportRequest) error
	Recv() (*ExportResponse, error)
	grpc.ClientStream
}

type streamExporterExportClient struct {
	grpc.ClientStream
}

func (x *streamExporterExportClient) Send(m *TraceExportRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *streamExporterExportClient) Recv() (*ExportResponse, error) {
	m := new(ExportResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// StreamExporterServer is the server API for StreamExporter service.
type StreamExporterServer interface {
	// Sends a batch of telemetry data.
	Export(StreamExporter_ExportServer) error
}

// UnimplementedStreamExporterServer can be embedded to have forward compatible implementations.
type UnimplementedStreamExporterServer struct {
}

func (*UnimplementedStreamExporterServer) Export(srv StreamExporter_ExportServer) error {
	return status.Errorf(codes.Unimplemented, "method Export not implemented")
}

func RegisterStreamExporterServer(s *grpc.Server, srv StreamExporterServer) {
	s.RegisterService(&_StreamExporter_serviceDesc, srv)
}

func _StreamExporter_Export_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StreamExporterServer).Export(&streamExporterExportServer{stream})
}

type StreamExporter_ExportServer interface {
	Send(*ExportResponse) error
	Recv() (*TraceExportRequest, error)
	grpc.ServerStream
}

type streamExporterExportServer struct {
	grpc.ServerStream
}

func (x *streamExporterExportServer) Send(m *ExportResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *streamExporterExportServer) Recv() (*TraceExportRequest, error) {
	m := new(TraceExportRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _StreamExporter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "otlp.StreamExporter",
	HandlerType: (*StreamExporterServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Export",
			Handler:       _StreamExporter_Export_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "grpc.proto",
}
