// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc.proto

package experimental

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("grpc.proto", fileDescriptor_bedfbfc9b54e5600) }

var fileDescriptor_bedfbfc9b54e5600 = []byte{
	// 197 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x8f, 0xbd, 0xae, 0x82, 0x30,
	0x14, 0xc7, 0x2f, 0x77, 0xb8, 0x43, 0xc3, 0x65, 0x60, 0x93, 0x30, 0x18, 0x27, 0xa7, 0x46, 0xf0,
	0x0d, 0x30, 0x26, 0x6e, 0x12, 0x45, 0xf7, 0xda, 0x1c, 0x91, 0x44, 0xda, 0xe3, 0x69, 0x31, 0xf8,
	0xca, 0x3e, 0x85, 0xa1, 0x8d, 0x46, 0x77, 0xb7, 0x93, 0xff, 0xd7, 0x2f, 0x87, 0xb1, 0x9a, 0x50,
	0x72, 0x24, 0x6d, 0x75, 0x1c, 0x42, 0x8f, 0x40, 0x4d, 0x0b, 0xca, 0x8a, 0x73, 0x12, 0x41, 0x2f,
	0x4f, 0x42, 0xd5, 0xe0, 0xdd, 0x5c, 0xb0, 0xff, 0x9d, 0x12, 0x74, 0x5b, 0xf6, 0xa8, 0xc9, 0x02,
	0xc5, 0x25, 0x0b, 0xfd, 0x5d, 0x91, 0x90, 0x60, 0xe2, 0x31, 0x7f, 0xef, 0x73, 0xa7, 0xfa, 0xc0,
	0x06, 0x2e, 0x1d, 0x18, 0x9b, 0xa4, 0x9f, 0x89, 0xa7, 0x69, 0x50, 0x2b, 0x03, 0x93, 0x9f, 0xfc,
	0xc8, 0xa2, 0xad, 0x25, 0x10, 0xed, 0x8b, 0x51, 0x7d, 0x9b, 0x31, 0x0d, 0x66, 0x41, 0xb1, 0x62,
	0x69, 0xa3, 0xb9, 0x46, 0x50, 0x12, 0x94, 0xe9, 0x8c, 0xff, 0x90, 0xdb, 0x61, 0x8d, 0x5f, 0xb3,
	0x82, 0xb9, 0xdd, 0x72, 0x10, 0xcb, 0xe0, 0xfe, 0x3b, 0x5a, 0x23, 0xa8, 0x85, 0x4f, 0x3a, 0xd1,
	0x73, 0xf9, 0x3e, 0x3b, 0xfc, 0xb9, 0xe6, 0xfc, 0x11, 0x00, 0x00, 0xff, 0xff, 0x69, 0x70, 0x09,
	0x02, 0x47, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UnaryExporterClient is the client API for UnaryExporter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UnaryExporterClient interface {
	ExportTraces(ctx context.Context, in *TraceExportRequest, opts ...grpc.CallOption) (*ExportResponse, error)
}

type unaryExporterClient struct {
	cc *grpc.ClientConn
}

func NewUnaryExporterClient(cc *grpc.ClientConn) UnaryExporterClient {
	return &unaryExporterClient{cc}
}

func (c *unaryExporterClient) ExportTraces(ctx context.Context, in *TraceExportRequest, opts ...grpc.CallOption) (*ExportResponse, error) {
	out := new(ExportResponse)
	err := c.cc.Invoke(ctx, "/experimental.UnaryExporter/ExportTraces", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UnaryExporterServer is the server API for UnaryExporter service.
type UnaryExporterServer interface {
	ExportTraces(context.Context, *TraceExportRequest) (*ExportResponse, error)
}

// UnimplementedUnaryExporterServer can be embedded to have forward compatible implementations.
type UnimplementedUnaryExporterServer struct {
}

func (*UnimplementedUnaryExporterServer) ExportTraces(ctx context.Context, req *TraceExportRequest) (*ExportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExportTraces not implemented")
}

func RegisterUnaryExporterServer(s *grpc.Server, srv UnaryExporterServer) {
	s.RegisterService(&_UnaryExporter_serviceDesc, srv)
}

func _UnaryExporter_ExportTraces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TraceExportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UnaryExporterServer).ExportTraces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/experimental.UnaryExporter/ExportTraces",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UnaryExporterServer).ExportTraces(ctx, req.(*TraceExportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UnaryExporter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "experimental.UnaryExporter",
	HandlerType: (*UnaryExporterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExportTraces",
			Handler:    _UnaryExporter_ExportTraces_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc.proto",
}

// StreamExporterClient is the client API for StreamExporter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StreamExporterClient interface {
	ExportTraces(ctx context.Context, opts ...grpc.CallOption) (StreamExporter_ExportTracesClient, error)
}

type streamExporterClient struct {
	cc *grpc.ClientConn
}

func NewStreamExporterClient(cc *grpc.ClientConn) StreamExporterClient {
	return &streamExporterClient{cc}
}

func (c *streamExporterClient) ExportTraces(ctx context.Context, opts ...grpc.CallOption) (StreamExporter_ExportTracesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_StreamExporter_serviceDesc.Streams[0], "/experimental.StreamExporter/ExportTraces", opts...)
	if err != nil {
		return nil, err
	}
	x := &streamExporterExportTracesClient{stream}
	return x, nil
}

type StreamExporter_ExportTracesClient interface {
	Send(*TraceExportRequest) error
	Recv() (*ExportResponse, error)
	grpc.ClientStream
}

type streamExporterExportTracesClient struct {
	grpc.ClientStream
}

func (x *streamExporterExportTracesClient) Send(m *TraceExportRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *streamExporterExportTracesClient) Recv() (*ExportResponse, error) {
	m := new(ExportResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// StreamExporterServer is the server API for StreamExporter service.
type StreamExporterServer interface {
	ExportTraces(StreamExporter_ExportTracesServer) error
}

// UnimplementedStreamExporterServer can be embedded to have forward compatible implementations.
type UnimplementedStreamExporterServer struct {
}

func (*UnimplementedStreamExporterServer) ExportTraces(srv StreamExporter_ExportTracesServer) error {
	return status.Errorf(codes.Unimplemented, "method ExportTraces not implemented")
}

func RegisterStreamExporterServer(s *grpc.Server, srv StreamExporterServer) {
	s.RegisterService(&_StreamExporter_serviceDesc, srv)
}

func _StreamExporter_ExportTraces_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StreamExporterServer).ExportTraces(&streamExporterExportTracesServer{stream})
}

type StreamExporter_ExportTracesServer interface {
	Send(*ExportResponse) error
	Recv() (*TraceExportRequest, error)
	grpc.ServerStream
}

type streamExporterExportTracesServer struct {
	grpc.ServerStream
}

func (x *streamExporterExportTracesServer) Send(m *ExportResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *streamExporterExportTracesServer) Recv() (*TraceExportRequest, error) {
	m := new(TraceExportRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _StreamExporter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "experimental.StreamExporter",
	HandlerType: (*StreamExporterServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExportTraces",
			Handler:       _StreamExporter_ExportTraces_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "grpc.proto",
}
