// Code generated by protoc-gen-go. DO NOT EDIT.
// source: metric_data.proto

package experimental

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The kind of metric. It describes how the data is reported.
//
// A gauge is an instantaneous measurement of a value.
//
// A counter/cumulative measurement is a value accumulated over a time
// interval. In a time series, cumulative measurements should have the same
// start time, increasing values and increasing end times, until an event
// resets the cumulative value to zero and sets a new start time for the
// following points.
type MetricDescriptor_Type int32

const (
	// Do not use this default value.
	MetricDescriptor_UNSPECIFIED MetricDescriptor_Type = 0
	// Integer gauge. The value can go both up and down.
	MetricDescriptor_GAUGE_INT64 MetricDescriptor_Type = 1
	// Floating point gauge. The value can go both up and down.
	MetricDescriptor_GAUGE_DOUBLE MetricDescriptor_Type = 2
	// Histogram gauge measurement. The count and sum can go both up and
	// down. Recorded values are always >= 0.
	// Used in scenarios like a snapshot of time the current items in a queue
	// have spent there.
	MetricDescriptor_GAUGE_HISTOGRAM MetricDescriptor_Type = 3
	// Integer counter measurement. The value cannot decrease, if resets
	// then the start_time should also be reset.
	MetricDescriptor_COUNTER_INT64 MetricDescriptor_Type = 4
	// Floating point counter measurement. The value cannot decrease, if
	// resets then the start_time should also be reset. Recorded values are
	// always >= 0.
	MetricDescriptor_COUNTER_DOUBLE MetricDescriptor_Type = 5
	// Histogram cumulative measurement. The count and sum cannot decrease,
	// if resets then the start_time should also be reset.
	MetricDescriptor_CUMULATIVE_HISTOGRAM MetricDescriptor_Type = 6
	// Some frameworks implemented Histograms as a summary of observations
	// (usually things like request durations and response sizes). While it
	// also provides a total count of observations and a sum of all observed
	// values, it calculates configurable percentiles over a sliding time
	// window. This is not recommended, since it cannot be aggregated.
	MetricDescriptor_SUMMARY MetricDescriptor_Type = 7
)

var MetricDescriptor_Type_name = map[int32]string{
	0: "UNSPECIFIED",
	1: "GAUGE_INT64",
	2: "GAUGE_DOUBLE",
	3: "GAUGE_HISTOGRAM",
	4: "COUNTER_INT64",
	5: "COUNTER_DOUBLE",
	6: "CUMULATIVE_HISTOGRAM",
	7: "SUMMARY",
}

var MetricDescriptor_Type_value = map[string]int32{
	"UNSPECIFIED":          0,
	"GAUGE_INT64":          1,
	"GAUGE_DOUBLE":         2,
	"GAUGE_HISTOGRAM":      3,
	"COUNTER_INT64":        4,
	"COUNTER_DOUBLE":       5,
	"CUMULATIVE_HISTOGRAM": 6,
	"SUMMARY":              7,
}

func (x MetricDescriptor_Type) String() string {
	return proto.EnumName(MetricDescriptor_Type_name, int32(x))
}

func (MetricDescriptor_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9a96a8671bd66caf, []int{2, 0}
}

// A list of metrics from a Resource.
type ResourceMetrics struct {
	Resource             *Resource `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	Metrics              []*Metric `protobuf:"bytes,2,rep,name=metrics,proto3" json:"metrics,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ResourceMetrics) Reset()         { *m = ResourceMetrics{} }
func (m *ResourceMetrics) String() string { return proto.CompactTextString(m) }
func (*ResourceMetrics) ProtoMessage()    {}
func (*ResourceMetrics) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a96a8671bd66caf, []int{0}
}

func (m *ResourceMetrics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourceMetrics.Unmarshal(m, b)
}
func (m *ResourceMetrics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourceMetrics.Marshal(b, m, deterministic)
}
func (m *ResourceMetrics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourceMetrics.Merge(m, src)
}
func (m *ResourceMetrics) XXX_Size() int {
	return xxx_messageInfo_ResourceMetrics.Size(m)
}
func (m *ResourceMetrics) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourceMetrics.DiscardUnknown(m)
}

var xxx_messageInfo_ResourceMetrics proto.InternalMessageInfo

func (m *ResourceMetrics) GetResource() *Resource {
	if m != nil {
		return m.Resource
	}
	return nil
}

func (m *ResourceMetrics) GetMetrics() []*Metric {
	if m != nil {
		return m.Metrics
	}
	return nil
}

// Defines a Metric which has one or more timeseries.
//
// The data model and relation between entities is shown in the diagram below.
//
// - Metric is composed of a Resource, a MetricDescriptor and a TimeSeriesList data.
// - MetricDescriptor contains a list of label keys (shown horizontally).
// - TimeSeriesList is composed of a list of TimeSeries (shown vertically).
// - TimeSeries contains a list of label values and a list of metric values (shown
//   horizontally).
//
//     Metric
//  +----------+         +--------+
//  |  resource|-------->|Resource|
//  |          |         +--------+
//  |          |
//  |          |         +------------------------+
//  |descriptor|-------->| MetricDescriptor       |
//  |          |         |+-----+-----+   +-----+ |
//  |          |         ||label|label|...|label| |
//  |      data|--+      ||key1 |key2 |   |keyN | |
//  +----------+  |      |+-----+-----+   +-----+ |
//                |      +------------------------+
//                |
//                |      +------------------------------+
//                |      |TimeSeries 1                  |
//                v      |+-----+-----+   +-----+       |
//             +-----+   ||label|label|...|label|       |
//             |  1  |-->|+-----+-----+   +-----+       |
//             +-----+   |+-----+-----+-----+   +-----+ |
//             |  .  |   ||value|value|value|...|value| |
//             |  .  |   |+-----+-----+-----+   +-----+ |
//             |  .  |   +------------------------------+
//             |  .  |                   .
//             |  .  |                   .
//             |  .  |                   .
//             |  .  |   +-----------------------------------+
//             |  .  |   |TimeSeries N                       |
//             +-----+   |+-----+-----+   +-----+            |
//             |  N  |-->||label|label|...|label|            |
//             +-----+   |+-----+-----+   +-----+            |
//                       |+-----+-----+-----+-----+   +-----+|
//                       ||value|value|value|value|...|value||
//                       |+-----+-----+-----+-----+   +-----+|
//                       +-----------------------------------+
//
//-----------------------------------------------------------------------
// TimeSeries contain an array of values, each value corresponding to a given moment in
// time. Each element of TimeSeries array is timestamped.
//
// TimeSeries are strongly typed: the element of a TimeSeries array has
// a specific Protobuf message depending on the value type of the metric and thus
// there are currently 4 TimeSeriesList and 4 TimeSeries messages, which
// correspond to the types of metric values.
// Defines a Metric which has one or more timeseries.
type Metric struct {
	// The descriptor of the Metric.
	MetricDescriptor *MetricDescriptor `protobuf:"bytes,1,opt,name=metric_descriptor,json=metricDescriptor,proto3" json:"metric_descriptor,omitempty"`
	// The resource for the metric. If unset, it may be set to a default value
	// provided for a sequence of messages in an RPC stream.
	Resource *Resource `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	// data is a list of one or more TimeSeries for a single metric, where each timeseries has
	// one or more points. Only one of the following fields is used for the data, depending on
	// the type of the metric defined by MetricDescriptor.type field.
	Int64Timeseries      []*Int64TimeSeries     `protobuf:"bytes,3,rep,name=int64_timeseries,json=int64Timeseries,proto3" json:"int64_timeseries,omitempty"`
	DoubleTimeseries     []*DoubleTimeSeries    `protobuf:"bytes,4,rep,name=double_timeseries,json=doubleTimeseries,proto3" json:"double_timeseries,omitempty"`
	HistogramTimeseries  []*HistogramTimeSeries `protobuf:"bytes,5,rep,name=histogram_timeseries,json=histogramTimeseries,proto3" json:"histogram_timeseries,omitempty"`
	SummaryTimeseries    []*SummaryTimeSeries   `protobuf:"bytes,6,rep,name=summary_timeseries,json=summaryTimeseries,proto3" json:"summary_timeseries,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Metric) Reset()         { *m = Metric{} }
func (m *Metric) String() string { return proto.CompactTextString(m) }
func (*Metric) ProtoMessage()    {}
func (*Metric) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a96a8671bd66caf, []int{1}
}

func (m *Metric) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metric.Unmarshal(m, b)
}
func (m *Metric) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metric.Marshal(b, m, deterministic)
}
func (m *Metric) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metric.Merge(m, src)
}
func (m *Metric) XXX_Size() int {
	return xxx_messageInfo_Metric.Size(m)
}
func (m *Metric) XXX_DiscardUnknown() {
	xxx_messageInfo_Metric.DiscardUnknown(m)
}

var xxx_messageInfo_Metric proto.InternalMessageInfo

func (m *Metric) GetMetricDescriptor() *MetricDescriptor {
	if m != nil {
		return m.MetricDescriptor
	}
	return nil
}

func (m *Metric) GetResource() *Resource {
	if m != nil {
		return m.Resource
	}
	return nil
}

func (m *Metric) GetInt64Timeseries() []*Int64TimeSeries {
	if m != nil {
		return m.Int64Timeseries
	}
	return nil
}

func (m *Metric) GetDoubleTimeseries() []*DoubleTimeSeries {
	if m != nil {
		return m.DoubleTimeseries
	}
	return nil
}

func (m *Metric) GetHistogramTimeseries() []*HistogramTimeSeries {
	if m != nil {
		return m.HistogramTimeseries
	}
	return nil
}

func (m *Metric) GetSummaryTimeseries() []*SummaryTimeSeries {
	if m != nil {
		return m.SummaryTimeseries
	}
	return nil
}

// Defines a metric type and its schema.
type MetricDescriptor struct {
	// The metric type, including its DNS name prefix. It must be unique.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// A detailed description of the metric, which can be used in documentation.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// The unit in which the metric value is reported. Follows the format
	// described by http://unitsofmeasure.org/ucum.html.
	Unit string                `protobuf:"bytes,3,opt,name=unit,proto3" json:"unit,omitempty"`
	Type MetricDescriptor_Type `protobuf:"varint,4,opt,name=type,proto3,enum=experimental.MetricDescriptor_Type" json:"type,omitempty"`
	// The label keys associated with the metric descriptor.
	LabelKeys            []string `protobuf:"bytes,5,rep,name=label_keys,json=labelKeys,proto3" json:"label_keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MetricDescriptor) Reset()         { *m = MetricDescriptor{} }
func (m *MetricDescriptor) String() string { return proto.CompactTextString(m) }
func (*MetricDescriptor) ProtoMessage()    {}
func (*MetricDescriptor) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a96a8671bd66caf, []int{2}
}

func (m *MetricDescriptor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetricDescriptor.Unmarshal(m, b)
}
func (m *MetricDescriptor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetricDescriptor.Marshal(b, m, deterministic)
}
func (m *MetricDescriptor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetricDescriptor.Merge(m, src)
}
func (m *MetricDescriptor) XXX_Size() int {
	return xxx_messageInfo_MetricDescriptor.Size(m)
}
func (m *MetricDescriptor) XXX_DiscardUnknown() {
	xxx_messageInfo_MetricDescriptor.DiscardUnknown(m)
}

var xxx_messageInfo_MetricDescriptor proto.InternalMessageInfo

func (m *MetricDescriptor) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MetricDescriptor) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *MetricDescriptor) GetUnit() string {
	if m != nil {
		return m.Unit
	}
	return ""
}

func (m *MetricDescriptor) GetType() MetricDescriptor_Type {
	if m != nil {
		return m.Type
	}
	return MetricDescriptor_UNSPECIFIED
}

func (m *MetricDescriptor) GetLabelKeys() []string {
	if m != nil {
		return m.LabelKeys
	}
	return nil
}

// Int64TimeSeries is a list of data points that describes the time-varying values
// of a int64 metric.
type Int64TimeSeries struct {
	// The set of label values that uniquely identify this timeseries. Applies to
	// all points. The order of label values must match that of label keys in the
	// metric descriptor.
	LabelValues []*LabelValue `protobuf:"bytes,1,rep,name=label_values,json=labelValues,proto3" json:"label_values,omitempty"`
	// The data points of this timeseries.
	Points               []*Int64Value `protobuf:"bytes,2,rep,name=points,proto3" json:"points,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Int64TimeSeries) Reset()         { *m = Int64TimeSeries{} }
func (m *Int64TimeSeries) String() string { return proto.CompactTextString(m) }
func (*Int64TimeSeries) ProtoMessage()    {}
func (*Int64TimeSeries) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a96a8671bd66caf, []int{3}
}

func (m *Int64TimeSeries) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Int64TimeSeries.Unmarshal(m, b)
}
func (m *Int64TimeSeries) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Int64TimeSeries.Marshal(b, m, deterministic)
}
func (m *Int64TimeSeries) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Int64TimeSeries.Merge(m, src)
}
func (m *Int64TimeSeries) XXX_Size() int {
	return xxx_messageInfo_Int64TimeSeries.Size(m)
}
func (m *Int64TimeSeries) XXX_DiscardUnknown() {
	xxx_messageInfo_Int64TimeSeries.DiscardUnknown(m)
}

var xxx_messageInfo_Int64TimeSeries proto.InternalMessageInfo

func (m *Int64TimeSeries) GetLabelValues() []*LabelValue {
	if m != nil {
		return m.LabelValues
	}
	return nil
}

func (m *Int64TimeSeries) GetPoints() []*Int64Value {
	if m != nil {
		return m.Points
	}
	return nil
}

// eDoubleTimeSeries is a list of data points that describes the time-varying values
// of a double metric.
type DoubleTimeSeries struct {
	// The set of label values that uniquely identify this timeseries. Applies to
	// all points. The order of label values must match that of label keys in the
	// metric descriptor.
	LabelValues []*LabelValue `protobuf:"bytes,1,rep,name=label_values,json=labelValues,proto3" json:"label_values,omitempty"`
	// The data points of this timeseries.
	Points               []*DoubleValue `protobuf:"bytes,2,rep,name=points,proto3" json:"points,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *DoubleTimeSeries) Reset()         { *m = DoubleTimeSeries{} }
func (m *DoubleTimeSeries) String() string { return proto.CompactTextString(m) }
func (*DoubleTimeSeries) ProtoMessage()    {}
func (*DoubleTimeSeries) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a96a8671bd66caf, []int{4}
}

func (m *DoubleTimeSeries) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DoubleTimeSeries.Unmarshal(m, b)
}
func (m *DoubleTimeSeries) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DoubleTimeSeries.Marshal(b, m, deterministic)
}
func (m *DoubleTimeSeries) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DoubleTimeSeries.Merge(m, src)
}
func (m *DoubleTimeSeries) XXX_Size() int {
	return xxx_messageInfo_DoubleTimeSeries.Size(m)
}
func (m *DoubleTimeSeries) XXX_DiscardUnknown() {
	xxx_messageInfo_DoubleTimeSeries.DiscardUnknown(m)
}

var xxx_messageInfo_DoubleTimeSeries proto.InternalMessageInfo

func (m *DoubleTimeSeries) GetLabelValues() []*LabelValue {
	if m != nil {
		return m.LabelValues
	}
	return nil
}

func (m *DoubleTimeSeries) GetPoints() []*DoubleValue {
	if m != nil {
		return m.Points
	}
	return nil
}

// HistogramTimeSeries is a list of data points that describes the time-varying values
// of a Histogram.
type HistogramTimeSeries struct {
	// The set of label values that uniquely identify this timeseries. Applies to
	// all points. The order of label values must match that of label keys in the
	// metric descriptor.
	LabelValues []*LabelValue `protobuf:"bytes,1,rep,name=label_values,json=labelValues,proto3" json:"label_values,omitempty"`
	// The data points of this timeseries.
	Points []*HistogramValue `protobuf:"bytes,2,rep,name=points,proto3" json:"points,omitempty"`
	// explicit_bounds is the only supported bucket option currently.
	ExplicitBounds       *HistogramTimeSeries_ExplicitBounds `protobuf:"bytes,3,opt,name=explicit_bounds,json=explicitBounds,proto3" json:"explicit_bounds,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                            `json:"-"`
	XXX_unrecognized     []byte                              `json:"-"`
	XXX_sizecache        int32                               `json:"-"`
}

func (m *HistogramTimeSeries) Reset()         { *m = HistogramTimeSeries{} }
func (m *HistogramTimeSeries) String() string { return proto.CompactTextString(m) }
func (*HistogramTimeSeries) ProtoMessage()    {}
func (*HistogramTimeSeries) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a96a8671bd66caf, []int{5}
}

func (m *HistogramTimeSeries) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HistogramTimeSeries.Unmarshal(m, b)
}
func (m *HistogramTimeSeries) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HistogramTimeSeries.Marshal(b, m, deterministic)
}
func (m *HistogramTimeSeries) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HistogramTimeSeries.Merge(m, src)
}
func (m *HistogramTimeSeries) XXX_Size() int {
	return xxx_messageInfo_HistogramTimeSeries.Size(m)
}
func (m *HistogramTimeSeries) XXX_DiscardUnknown() {
	xxx_messageInfo_HistogramTimeSeries.DiscardUnknown(m)
}

var xxx_messageInfo_HistogramTimeSeries proto.InternalMessageInfo

func (m *HistogramTimeSeries) GetLabelValues() []*LabelValue {
	if m != nil {
		return m.LabelValues
	}
	return nil
}

func (m *HistogramTimeSeries) GetPoints() []*HistogramValue {
	if m != nil {
		return m.Points
	}
	return nil
}

func (m *HistogramTimeSeries) GetExplicitBounds() *HistogramTimeSeries_ExplicitBounds {
	if m != nil {
		return m.ExplicitBounds
	}
	return nil
}

// ExplicitBounds specifies buckets with explicitly defined bounds for values.
type HistogramTimeSeries_ExplicitBounds struct {
	// The bucket boundaries are described by "bounds" field.
	//
	// This defines size(bounds) + 1 (= N) buckets. The boundaries for bucket
	// at index i are:
	//
	// [0, bounds[i]) for i == 0
	// [bounds[i-1], bounds[i]) for 0 < i < N-1
	// [bounds[i], +infinity) for i == N-1
	// The values in bounds array must be strictly increasing and > 0.
	//
	// Note: only [a, b) intervals are currently supported for each bucket. If we decides
	// to also support (a, b] intervals we should add support for these by defining a boolean
	// value which decides what type of intervals to use.
	Bounds               []float64 `protobuf:"fixed64,1,rep,packed,name=bounds,proto3" json:"bounds,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *HistogramTimeSeries_ExplicitBounds) Reset()         { *m = HistogramTimeSeries_ExplicitBounds{} }
func (m *HistogramTimeSeries_ExplicitBounds) String() string { return proto.CompactTextString(m) }
func (*HistogramTimeSeries_ExplicitBounds) ProtoMessage()    {}
func (*HistogramTimeSeries_ExplicitBounds) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a96a8671bd66caf, []int{5, 0}
}

func (m *HistogramTimeSeries_ExplicitBounds) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HistogramTimeSeries_ExplicitBounds.Unmarshal(m, b)
}
func (m *HistogramTimeSeries_ExplicitBounds) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HistogramTimeSeries_ExplicitBounds.Marshal(b, m, deterministic)
}
func (m *HistogramTimeSeries_ExplicitBounds) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HistogramTimeSeries_ExplicitBounds.Merge(m, src)
}
func (m *HistogramTimeSeries_ExplicitBounds) XXX_Size() int {
	return xxx_messageInfo_HistogramTimeSeries_ExplicitBounds.Size(m)
}
func (m *HistogramTimeSeries_ExplicitBounds) XXX_DiscardUnknown() {
	xxx_messageInfo_HistogramTimeSeries_ExplicitBounds.DiscardUnknown(m)
}

var xxx_messageInfo_HistogramTimeSeries_ExplicitBounds proto.InternalMessageInfo

func (m *HistogramTimeSeries_ExplicitBounds) GetBounds() []float64 {
	if m != nil {
		return m.Bounds
	}
	return nil
}

// SummaryTimeSeries is a list of data points that describes the time-varying values
// of a Summary metric.
type SummaryTimeSeries struct {
	// The set of label values that uniquely identify this timeseries. Applies to
	// all points. The order of label values must match that of label keys in the
	// metric descriptor.
	LabelValues []*LabelValue `protobuf:"bytes,1,rep,name=label_values,json=labelValues,proto3" json:"label_values,omitempty"`
	// The data points of this timeseries.
	Points               []*SummaryValue `protobuf:"bytes,2,rep,name=points,proto3" json:"points,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SummaryTimeSeries) Reset()         { *m = SummaryTimeSeries{} }
func (m *SummaryTimeSeries) String() string { return proto.CompactTextString(m) }
func (*SummaryTimeSeries) ProtoMessage()    {}
func (*SummaryTimeSeries) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a96a8671bd66caf, []int{6}
}

func (m *SummaryTimeSeries) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SummaryTimeSeries.Unmarshal(m, b)
}
func (m *SummaryTimeSeries) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SummaryTimeSeries.Marshal(b, m, deterministic)
}
func (m *SummaryTimeSeries) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SummaryTimeSeries.Merge(m, src)
}
func (m *SummaryTimeSeries) XXX_Size() int {
	return xxx_messageInfo_SummaryTimeSeries.Size(m)
}
func (m *SummaryTimeSeries) XXX_DiscardUnknown() {
	xxx_messageInfo_SummaryTimeSeries.DiscardUnknown(m)
}

var xxx_messageInfo_SummaryTimeSeries proto.InternalMessageInfo

func (m *SummaryTimeSeries) GetLabelValues() []*LabelValue {
	if m != nil {
		return m.LabelValues
	}
	return nil
}

func (m *SummaryTimeSeries) GetPoints() []*SummaryValue {
	if m != nil {
		return m.Points
	}
	return nil
}

type LabelValue struct {
	// The value for the label.
	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	// If false the value field is ignored and considered not set.
	// This is used to differentiate a missing label from an empty string.
	HasValue             bool     `protobuf:"varint,2,opt,name=has_value,json=hasValue,proto3" json:"has_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LabelValue) Reset()         { *m = LabelValue{} }
func (m *LabelValue) String() string { return proto.CompactTextString(m) }
func (*LabelValue) ProtoMessage()    {}
func (*LabelValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a96a8671bd66caf, []int{7}
}

func (m *LabelValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LabelValue.Unmarshal(m, b)
}
func (m *LabelValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LabelValue.Marshal(b, m, deterministic)
}
func (m *LabelValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LabelValue.Merge(m, src)
}
func (m *LabelValue) XXX_Size() int {
	return xxx_messageInfo_LabelValue.Size(m)
}
func (m *LabelValue) XXX_DiscardUnknown() {
	xxx_messageInfo_LabelValue.DiscardUnknown(m)
}

var xxx_messageInfo_LabelValue proto.InternalMessageInfo

func (m *LabelValue) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *LabelValue) GetHasValue() bool {
	if m != nil {
		return m.HasValue
	}
	return false
}

// Int64Value is a timestamped measurement of int64 value.
type Int64Value struct {
	// start_time_unixnano is the time when the cumulative value was reset to zero.
	// This is used for Counter type only. For Gauge the value is not specified and
	// defaults to 0.
	//
	// The cumulative value is over the time interval (start_time_unixnano, timestamp_unixnano].
	// Value is UNIX Epoch time in nanoseconds since 00:00:00 UTC on 1 January 1970.
	//
	// Value of 0 indicates that the start_time is the same as that of the previous
	// data point in this timeseries. When creating timeseries of this type it is recommended
	// to omit this value if the start_time does not change, since it results in more
	// compact encoding on the wire.
	// If the value of 0 occurs for the first data point in the timeseries it means that
	// the timestamp is unspecified. In that case the timestamp may be decided by the backend.
	StartTimeUnixnano int64 `protobuf:"fixed64,1,opt,name=start_time_unixnano,json=startTimeUnixnano,proto3" json:"start_time_unixnano,omitempty"`
	// timestamp_unixnano is the moment when this value was recorded.
	// Value is UNIX Epoch time in nanoseconds since 00:00:00 UTC on 1 January 1970.
	TimestampUnixnano int64 `protobuf:"fixed64,2,opt,name=timestamp_unixnano,json=timestampUnixnano,proto3" json:"timestamp_unixnano,omitempty"`
	// value itself.
	Value                int64    `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Int64Value) Reset()         { *m = Int64Value{} }
func (m *Int64Value) String() string { return proto.CompactTextString(m) }
func (*Int64Value) ProtoMessage()    {}
func (*Int64Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a96a8671bd66caf, []int{8}
}

func (m *Int64Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Int64Value.Unmarshal(m, b)
}
func (m *Int64Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Int64Value.Marshal(b, m, deterministic)
}
func (m *Int64Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Int64Value.Merge(m, src)
}
func (m *Int64Value) XXX_Size() int {
	return xxx_messageInfo_Int64Value.Size(m)
}
func (m *Int64Value) XXX_DiscardUnknown() {
	xxx_messageInfo_Int64Value.DiscardUnknown(m)
}

var xxx_messageInfo_Int64Value proto.InternalMessageInfo

func (m *Int64Value) GetStartTimeUnixnano() int64 {
	if m != nil {
		return m.StartTimeUnixnano
	}
	return 0
}

func (m *Int64Value) GetTimestampUnixnano() int64 {
	if m != nil {
		return m.TimestampUnixnano
	}
	return 0
}

func (m *Int64Value) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

// DoubleValue is a timestamped measurement of double value.
type DoubleValue struct {
	// start_time_unixnano is the time when the cumulative value was reset to zero.
	// This is used for Counter type only. For Gauge the value is not specified and
	// defaults to 0.
	//
	// The cumulative value is over the time interval (start_time_unixnano, timestamp_unixnano].
	// Value is UNIX Epoch time in nanoseconds since 00:00:00 UTC on 1 January 1970.
	//
	// Value of 0 indicates that the start_time is the same as that of the previous
	// data point in this timeseries. When creating timeseries of this type it is recommended
	// to omit this value if the start_time does not change, since it results in more
	// compact encoding on the wire.
	// If the value of 0 occurs for the first data point in the timeseries it means that
	// the timestamp is unspecified. In that case the timestamp may be decided by the backend.
	StartTimeUnixnano int64 `protobuf:"fixed64,1,opt,name=start_time_unixnano,json=startTimeUnixnano,proto3" json:"start_time_unixnano,omitempty"`
	// timestamp_unixnano is the moment when this value was recorded.
	// Value is UNIX Epoch time in nanoseconds since 00:00:00 UTC on 1 January 1970.
	TimestampUnixnano int64 `protobuf:"fixed64,2,opt,name=timestamp_unixnano,json=timestampUnixnano,proto3" json:"timestamp_unixnano,omitempty"`
	// value itself.
	Value                float64  `protobuf:"fixed64,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DoubleValue) Reset()         { *m = DoubleValue{} }
func (m *DoubleValue) String() string { return proto.CompactTextString(m) }
func (*DoubleValue) ProtoMessage()    {}
func (*DoubleValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a96a8671bd66caf, []int{9}
}

func (m *DoubleValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DoubleValue.Unmarshal(m, b)
}
func (m *DoubleValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DoubleValue.Marshal(b, m, deterministic)
}
func (m *DoubleValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DoubleValue.Merge(m, src)
}
func (m *DoubleValue) XXX_Size() int {
	return xxx_messageInfo_DoubleValue.Size(m)
}
func (m *DoubleValue) XXX_DiscardUnknown() {
	xxx_messageInfo_DoubleValue.DiscardUnknown(m)
}

var xxx_messageInfo_DoubleValue proto.InternalMessageInfo

func (m *DoubleValue) GetStartTimeUnixnano() int64 {
	if m != nil {
		return m.StartTimeUnixnano
	}
	return 0
}

func (m *DoubleValue) GetTimestampUnixnano() int64 {
	if m != nil {
		return m.TimestampUnixnano
	}
	return 0
}

func (m *DoubleValue) GetValue() float64 {
	if m != nil {
		return m.Value
	}
	return 0
}

// HistogramValue contains summary statistics for a population of values. It may
// optionally contain the distribution of those values across a set of buckets.
type HistogramValue struct {
	// start_time_unixnano is the time when the cumulative value was reset to zero.
	// The cumulative value is over the time interval [start_time_unixnano, timestamp_unixnano].
	// Value is UNIX Epoch time in nanoseconds since 00:00:00 UTC on 1 January 1970.
	//
	// Value of 0 indicates that the start_time is the same as that of the previous
	// data point in this timeseries. When creating timeseries of this type it is recommended
	// to omit this value if the start_time does not change, since it results in more
	// compact encoding on the wire.
	// If the value of 0 occurs for the first data point in the timeseries it means that
	// the timestamp is unspecified. In that case the timestamp may be decided by the backend.
	// Note: this field is always unspecified and ignored if MetricDescriptor.type==GAUGE_HISTOGRAM.
	StartTimeUnixnano int64 `protobuf:"fixed64,1,opt,name=start_time_unixnano,json=startTimeUnixnano,proto3" json:"start_time_unixnano,omitempty"`
	// timestamp_unixnano is the moment when this value was recorded.
	// Value is UNIX Epoch time in nanoseconds since 00:00:00 UTC on 1 January 1970.
	TimestampUnixnano int64 `protobuf:"fixed64,2,opt,name=timestamp_unixnano,json=timestampUnixnano,proto3" json:"timestamp_unixnano,omitempty"`
	// count is the number of values in the population. Must be non-negative. This value
	// must be equal to the sum of the "count" fields in buckets if a histogram is
	// provided.
	Count int64 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	// sum of the values in the population. If count is zero then this field
	// must be zero. This value must be equal to the sum of the "sum" fields in buckets if
	// a histogram is provided.
	Sum float64 `protobuf:"fixed64,4,opt,name=sum,proto3" json:"sum,omitempty"`
	// buckets is an optional field contains the values of histogram for each bucket.
	//
	// The sum of the values in the buckets "count" field must equal the value in the
	// count field of HistogramValue.
	//
	// The number of elements in buckets array must be by one greater than the
	// number of elements in bucket_bounds array.
	//
	// Note: if HistogramTimeSeries.bucket_options defines bucket bounds then this field
	// must also be present and number of elements in this field must be equal to the
	// number of buckets defined by bucket_options.
	Buckets              []*HistogramValue_Bucket `protobuf:"bytes,5,rep,name=buckets,proto3" json:"buckets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *HistogramValue) Reset()         { *m = HistogramValue{} }
func (m *HistogramValue) String() string { return proto.CompactTextString(m) }
func (*HistogramValue) ProtoMessage()    {}
func (*HistogramValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a96a8671bd66caf, []int{10}
}

func (m *HistogramValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HistogramValue.Unmarshal(m, b)
}
func (m *HistogramValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HistogramValue.Marshal(b, m, deterministic)
}
func (m *HistogramValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HistogramValue.Merge(m, src)
}
func (m *HistogramValue) XXX_Size() int {
	return xxx_messageInfo_HistogramValue.Size(m)
}
func (m *HistogramValue) XXX_DiscardUnknown() {
	xxx_messageInfo_HistogramValue.DiscardUnknown(m)
}

var xxx_messageInfo_HistogramValue proto.InternalMessageInfo

func (m *HistogramValue) GetStartTimeUnixnano() int64 {
	if m != nil {
		return m.StartTimeUnixnano
	}
	return 0
}

func (m *HistogramValue) GetTimestampUnixnano() int64 {
	if m != nil {
		return m.TimestampUnixnano
	}
	return 0
}

func (m *HistogramValue) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *HistogramValue) GetSum() float64 {
	if m != nil {
		return m.Sum
	}
	return 0
}

func (m *HistogramValue) GetBuckets() []*HistogramValue_Bucket {
	if m != nil {
		return m.Buckets
	}
	return nil
}

// Bucket contains values for a bucket.
type HistogramValue_Bucket struct {
	// The number of values in each bucket of the histogram, as described by
	// bucket_options.
	Count int64 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	// exemplar is an optional representative value of the bucket.
	Exemplar             *HistogramValue_Bucket_Exemplar `protobuf:"bytes,2,opt,name=exemplar,proto3" json:"exemplar,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *HistogramValue_Bucket) Reset()         { *m = HistogramValue_Bucket{} }
func (m *HistogramValue_Bucket) String() string { return proto.CompactTextString(m) }
func (*HistogramValue_Bucket) ProtoMessage()    {}
func (*HistogramValue_Bucket) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a96a8671bd66caf, []int{10, 0}
}

func (m *HistogramValue_Bucket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HistogramValue_Bucket.Unmarshal(m, b)
}
func (m *HistogramValue_Bucket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HistogramValue_Bucket.Marshal(b, m, deterministic)
}
func (m *HistogramValue_Bucket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HistogramValue_Bucket.Merge(m, src)
}
func (m *HistogramValue_Bucket) XXX_Size() int {
	return xxx_messageInfo_HistogramValue_Bucket.Size(m)
}
func (m *HistogramValue_Bucket) XXX_DiscardUnknown() {
	xxx_messageInfo_HistogramValue_Bucket.DiscardUnknown(m)
}

var xxx_messageInfo_HistogramValue_Bucket proto.InternalMessageInfo

func (m *HistogramValue_Bucket) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *HistogramValue_Bucket) GetExemplar() *HistogramValue_Bucket_Exemplar {
	if m != nil {
		return m.Exemplar
	}
	return nil
}

// Exemplars are example points that may be used to annotate aggregated
// Histogram values. They are metadata that gives information about a
// particular value added to a Histogram bucket.
type HistogramValue_Bucket_Exemplar struct {
	// Value of the exemplar point. It determines which bucket the exemplar belongs to.
	// If bucket_options define bounds for this bucket then this value must be within
	// the defined bounds.
	Value float64 `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	// timestamp_unixnano is the moment when this exemplar was recorded.
	// Value is UNIX Epoch time in nanoseconds since 00:00:00 UTC on 1 January 1970.
	TimestampUnixnano int64 `protobuf:"fixed64,2,opt,name=timestamp_unixnano,json=timestampUnixnano,proto3" json:"timestamp_unixnano,omitempty"`
	// exemplar_attachments are contextual information about the example value.
	// Keys in this list must be unique.
	Attachments          []*StringKeyValuePair `protobuf:"bytes,3,rep,name=attachments,proto3" json:"attachments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *HistogramValue_Bucket_Exemplar) Reset()         { *m = HistogramValue_Bucket_Exemplar{} }
func (m *HistogramValue_Bucket_Exemplar) String() string { return proto.CompactTextString(m) }
func (*HistogramValue_Bucket_Exemplar) ProtoMessage()    {}
func (*HistogramValue_Bucket_Exemplar) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a96a8671bd66caf, []int{10, 0, 0}
}

func (m *HistogramValue_Bucket_Exemplar) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HistogramValue_Bucket_Exemplar.Unmarshal(m, b)
}
func (m *HistogramValue_Bucket_Exemplar) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HistogramValue_Bucket_Exemplar.Marshal(b, m, deterministic)
}
func (m *HistogramValue_Bucket_Exemplar) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HistogramValue_Bucket_Exemplar.Merge(m, src)
}
func (m *HistogramValue_Bucket_Exemplar) XXX_Size() int {
	return xxx_messageInfo_HistogramValue_Bucket_Exemplar.Size(m)
}
func (m *HistogramValue_Bucket_Exemplar) XXX_DiscardUnknown() {
	xxx_messageInfo_HistogramValue_Bucket_Exemplar.DiscardUnknown(m)
}

var xxx_messageInfo_HistogramValue_Bucket_Exemplar proto.InternalMessageInfo

func (m *HistogramValue_Bucket_Exemplar) GetValue() float64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *HistogramValue_Bucket_Exemplar) GetTimestampUnixnano() int64 {
	if m != nil {
		return m.TimestampUnixnano
	}
	return 0
}

func (m *HistogramValue_Bucket_Exemplar) GetAttachments() []*StringKeyValuePair {
	if m != nil {
		return m.Attachments
	}
	return nil
}

// StringKeyValuePair is a pair of key/value strings.
type StringKeyValuePair struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringKeyValuePair) Reset()         { *m = StringKeyValuePair{} }
func (m *StringKeyValuePair) String() string { return proto.CompactTextString(m) }
func (*StringKeyValuePair) ProtoMessage()    {}
func (*StringKeyValuePair) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a96a8671bd66caf, []int{11}
}

func (m *StringKeyValuePair) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringKeyValuePair.Unmarshal(m, b)
}
func (m *StringKeyValuePair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringKeyValuePair.Marshal(b, m, deterministic)
}
func (m *StringKeyValuePair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringKeyValuePair.Merge(m, src)
}
func (m *StringKeyValuePair) XXX_Size() int {
	return xxx_messageInfo_StringKeyValuePair.Size(m)
}
func (m *StringKeyValuePair) XXX_DiscardUnknown() {
	xxx_messageInfo_StringKeyValuePair.DiscardUnknown(m)
}

var xxx_messageInfo_StringKeyValuePair proto.InternalMessageInfo

func (m *StringKeyValuePair) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *StringKeyValuePair) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// The start_timestamp only applies to the count and sum in the SummaryValue.
type SummaryValue struct {
	// start_time_unixnano is the time when the cumulative value was reset to zero.
	// This is used for Counter type only. For Gauge the value is not specified and
	// defaults to 0.
	//
	// The cumulative value is over the time interval (start_time_unixnano, timestamp_unixnano].
	// Value is UNIX Epoch time in nanoseconds since 00:00:00 UTC on 1 January 1970.
	//
	// Value of 0 indicates that the start_time is the same as that of the previous
	// data point in this timeseries. When creating timeseries of this type it is recommended
	// to omit this value if the start_time does not change, since it results in more
	// compact encoding on the wire.
	// If the value of 0 occurs for the first data point in the timeseries it means that
	// the timestamp is unspecified. In that case the timestamp may be decided by the backend.
	StartTimeUnixnano int64 `protobuf:"fixed64,1,opt,name=start_time_unixnano,json=startTimeUnixnano,proto3" json:"start_time_unixnano,omitempty"`
	// timestamp_unixnano is the moment when this value was recorded.
	// Value is UNIX Epoch time in nanoseconds since 00:00:00 UTC on 1 January 1970.
	TimestampUnixnano int64 `protobuf:"fixed64,2,opt,name=timestamp_unixnano,json=timestampUnixnano,proto3" json:"timestamp_unixnano,omitempty"`
	// The total number of recorded values since start_time. Optional since
	// some systems don't expose this.
	Count int64 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	// The total sum of recorded values since start_time. Optional since some
	// systems don't expose this. If count is zero then this field must be zero.
	Sum float64 `protobuf:"fixed64,4,opt,name=sum,proto3" json:"sum,omitempty"`
	// count_and_sum_unspecified must be set to true if count and sum values are unknown or
	// unspecified.
	CountAndSumUnspecified bool `protobuf:"varint,5,opt,name=count_and_sum_unspecified,json=countAndSumUnspecified,proto3" json:"count_and_sum_unspecified,omitempty"`
	// A list of values at different percentiles of the distribution calculated
	// from the current snapshot. The percentiles must be strictly increasing.
	PercentileValues     []*SummaryValue_ValueAtPercentile `protobuf:"bytes,6,rep,name=percentile_values,json=percentileValues,proto3" json:"percentile_values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *SummaryValue) Reset()         { *m = SummaryValue{} }
func (m *SummaryValue) String() string { return proto.CompactTextString(m) }
func (*SummaryValue) ProtoMessage()    {}
func (*SummaryValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a96a8671bd66caf, []int{12}
}

func (m *SummaryValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SummaryValue.Unmarshal(m, b)
}
func (m *SummaryValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SummaryValue.Marshal(b, m, deterministic)
}
func (m *SummaryValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SummaryValue.Merge(m, src)
}
func (m *SummaryValue) XXX_Size() int {
	return xxx_messageInfo_SummaryValue.Size(m)
}
func (m *SummaryValue) XXX_DiscardUnknown() {
	xxx_messageInfo_SummaryValue.DiscardUnknown(m)
}

var xxx_messageInfo_SummaryValue proto.InternalMessageInfo

func (m *SummaryValue) GetStartTimeUnixnano() int64 {
	if m != nil {
		return m.StartTimeUnixnano
	}
	return 0
}

func (m *SummaryValue) GetTimestampUnixnano() int64 {
	if m != nil {
		return m.TimestampUnixnano
	}
	return 0
}

func (m *SummaryValue) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *SummaryValue) GetSum() float64 {
	if m != nil {
		return m.Sum
	}
	return 0
}

func (m *SummaryValue) GetCountAndSumUnspecified() bool {
	if m != nil {
		return m.CountAndSumUnspecified
	}
	return false
}

func (m *SummaryValue) GetPercentileValues() []*SummaryValue_ValueAtPercentile {
	if m != nil {
		return m.PercentileValues
	}
	return nil
}

// Represents the value at a given percentile of a distribution.
type SummaryValue_ValueAtPercentile struct {
	// The percentile of a distribution. Must be in the interval
	// (0.0, 100.0].
	Percentile float64 `protobuf:"fixed64,1,opt,name=percentile,proto3" json:"percentile,omitempty"`
	// The value at the given percentile of a distribution.
	Value                float64  `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SummaryValue_ValueAtPercentile) Reset()         { *m = SummaryValue_ValueAtPercentile{} }
func (m *SummaryValue_ValueAtPercentile) String() string { return proto.CompactTextString(m) }
func (*SummaryValue_ValueAtPercentile) ProtoMessage()    {}
func (*SummaryValue_ValueAtPercentile) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a96a8671bd66caf, []int{12, 0}
}

func (m *SummaryValue_ValueAtPercentile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SummaryValue_ValueAtPercentile.Unmarshal(m, b)
}
func (m *SummaryValue_ValueAtPercentile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SummaryValue_ValueAtPercentile.Marshal(b, m, deterministic)
}
func (m *SummaryValue_ValueAtPercentile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SummaryValue_ValueAtPercentile.Merge(m, src)
}
func (m *SummaryValue_ValueAtPercentile) XXX_Size() int {
	return xxx_messageInfo_SummaryValue_ValueAtPercentile.Size(m)
}
func (m *SummaryValue_ValueAtPercentile) XXX_DiscardUnknown() {
	xxx_messageInfo_SummaryValue_ValueAtPercentile.DiscardUnknown(m)
}

var xxx_messageInfo_SummaryValue_ValueAtPercentile proto.InternalMessageInfo

func (m *SummaryValue_ValueAtPercentile) GetPercentile() float64 {
	if m != nil {
		return m.Percentile
	}
	return 0
}

func (m *SummaryValue_ValueAtPercentile) GetValue() float64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func init() {
	proto.RegisterEnum("experimental.MetricDescriptor_Type", MetricDescriptor_Type_name, MetricDescriptor_Type_value)
	proto.RegisterType((*ResourceMetrics)(nil), "experimental.ResourceMetrics")
	proto.RegisterType((*Metric)(nil), "experimental.Metric")
	proto.RegisterType((*MetricDescriptor)(nil), "experimental.MetricDescriptor")
	proto.RegisterType((*Int64TimeSeries)(nil), "experimental.Int64TimeSeries")
	proto.RegisterType((*DoubleTimeSeries)(nil), "experimental.DoubleTimeSeries")
	proto.RegisterType((*HistogramTimeSeries)(nil), "experimental.HistogramTimeSeries")
	proto.RegisterType((*HistogramTimeSeries_ExplicitBounds)(nil), "experimental.HistogramTimeSeries.ExplicitBounds")
	proto.RegisterType((*SummaryTimeSeries)(nil), "experimental.SummaryTimeSeries")
	proto.RegisterType((*LabelValue)(nil), "experimental.LabelValue")
	proto.RegisterType((*Int64Value)(nil), "experimental.Int64Value")
	proto.RegisterType((*DoubleValue)(nil), "experimental.DoubleValue")
	proto.RegisterType((*HistogramValue)(nil), "experimental.HistogramValue")
	proto.RegisterType((*HistogramValue_Bucket)(nil), "experimental.HistogramValue.Bucket")
	proto.RegisterType((*HistogramValue_Bucket_Exemplar)(nil), "experimental.HistogramValue.Bucket.Exemplar")
	proto.RegisterType((*StringKeyValuePair)(nil), "experimental.StringKeyValuePair")
	proto.RegisterType((*SummaryValue)(nil), "experimental.SummaryValue")
	proto.RegisterType((*SummaryValue_ValueAtPercentile)(nil), "experimental.SummaryValue.ValueAtPercentile")
}

func init() { proto.RegisterFile("metric_data.proto", fileDescriptor_9a96a8671bd66caf) }

var fileDescriptor_9a96a8671bd66caf = []byte{
	// 1064 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x56, 0x4d, 0x6f, 0xe3, 0x44,
	0x18, 0xc6, 0x49, 0x9a, 0xb6, 0x6f, 0x4a, 0xe3, 0x4c, 0xab, 0x95, 0x1b, 0x76, 0x4b, 0xf1, 0x5e,
	0x7a, 0x58, 0xbc, 0xdb, 0x50, 0x2d, 0x42, 0x80, 0x50, 0xd2, 0x86, 0x36, 0xea, 0xa7, 0x26, 0x49,
	0xa5, 0x9e, 0xa2, 0x89, 0x33, 0xdb, 0x8e, 0xea, 0x2f, 0x79, 0xc6, 0x4b, 0x73, 0x03, 0xc4, 0x95,
	0x13, 0x67, 0xfe, 0x0e, 0xbf, 0x00, 0x89, 0xff, 0xc0, 0x0f, 0xe0, 0x88, 0x90, 0x67, 0xec, 0xd8,
	0x4e, 0xbb, 0xcb, 0xa2, 0x4a, 0x2b, 0x2e, 0xd1, 0xcc, 0x33, 0xcf, 0xf3, 0xcc, 0x3b, 0xef, 0xbc,
	0xef, 0xc4, 0xd0, 0x70, 0xa9, 0x08, 0x99, 0x3d, 0x9a, 0x10, 0x41, 0xac, 0x20, 0xf4, 0x85, 0x8f,
	0x56, 0xe8, 0x6d, 0x40, 0x43, 0xe6, 0x52, 0x4f, 0x10, 0xa7, 0xb9, 0x2e, 0xa8, 0x43, 0x63, 0xd2,
	0x34, 0xc7, 0x69, 0x6e, 0x5e, 0xf9, 0xfe, 0x95, 0x43, 0x9f, 0xcb, 0xd9, 0x38, 0x7a, 0xf5, 0xfc,
	0xbb, 0x90, 0x04, 0x01, 0x0d, 0xb9, 0x5a, 0x37, 0x23, 0xa8, 0x63, 0xca, 0xfd, 0x28, 0xb4, 0xe9,
	0x89, 0xdc, 0x80, 0xa3, 0x16, 0x2c, 0x85, 0x09, 0x64, 0x68, 0x5b, 0xda, 0x76, 0xad, 0xf5, 0xc8,
	0xca, 0xef, 0x64, 0xa5, 0x02, 0x3c, 0xe3, 0x21, 0x0b, 0x16, 0x55, 0x7c, 0xdc, 0x28, 0x6d, 0x95,
	0xb7, 0x6b, 0xad, 0xf5, 0xa2, 0x44, 0x79, 0xe3, 0x94, 0x64, 0xfe, 0x56, 0x86, 0xaa, 0xc2, 0xd0,
	0x51, 0x76, 0x34, 0xca, 0xed, 0x90, 0x05, 0xc2, 0x0f, 0x93, 0x7d, 0x37, 0xef, 0x33, 0xd9, 0x9f,
	0xb1, 0xb0, 0xee, 0xce, 0x21, 0x85, 0xd8, 0x4b, 0xef, 0x18, 0xfb, 0x21, 0xe8, 0xcc, 0x13, 0x2f,
	0x77, 0x47, 0x82, 0xb9, 0x94, 0xd3, 0x90, 0x51, 0x6e, 0x94, 0xe5, 0x21, 0x9e, 0x14, 0xb5, 0xbd,
	0x98, 0x35, 0x60, 0x2e, 0xed, 0x4b, 0x12, 0xae, 0xb3, 0x14, 0x50, 0xaa, 0xf8, 0x28, 0x13, 0x3f,
	0x1a, 0x3b, 0x34, 0x6f, 0x55, 0x91, 0x56, 0x73, 0x47, 0xd9, 0x97, 0xb4, 0x9c, 0x97, 0x3e, 0x99,
	0x21, 0x89, 0xd9, 0x00, 0xd6, 0xaf, 0x19, 0x17, 0xfe, 0x55, 0x48, 0xdc, 0xbc, 0xdf, 0x82, 0xf4,
	0xfb, 0xa4, 0xe8, 0x77, 0x98, 0x32, 0x73, 0x96, 0x6b, 0xd7, 0x79, 0x30, 0x71, 0x3d, 0x05, 0xc4,
	0x23, 0xd7, 0x25, 0xe1, 0x34, 0xef, 0x59, 0x95, 0x9e, 0x1f, 0x17, 0x3d, 0xfb, 0x8a, 0x97, 0x73,
	0x6c, 0xf0, 0x0c, 0x52, 0x4a, 0xf3, 0xf7, 0x12, 0xe8, 0xf3, 0xf7, 0x82, 0x10, 0x54, 0x3c, 0xe2,
	0xaa, 0xea, 0x59, 0xc6, 0x72, 0x8c, 0xb6, 0xa0, 0x96, 0xde, 0x2f, 0xf3, 0x3d, 0x79, 0x39, 0xcb,
	0x38, 0x0f, 0xc5, 0xaa, 0xc8, 0x63, 0xc2, 0x28, 0x2b, 0x55, 0x3c, 0x46, 0x9f, 0x43, 0x45, 0x4c,
	0x03, 0x6a, 0x54, 0xb6, 0xb4, 0xed, 0xd5, 0xd6, 0xd3, 0xb7, 0xd7, 0x83, 0x35, 0x98, 0x06, 0x14,
	0x4b, 0x01, 0x7a, 0x02, 0xe0, 0x90, 0x31, 0x75, 0x46, 0x37, 0x74, 0xaa, 0x72, 0xb6, 0x8c, 0x97,
	0x25, 0x72, 0x44, 0xa7, 0xdc, 0xfc, 0x55, 0x83, 0x4a, 0xcc, 0x46, 0x75, 0xa8, 0x0d, 0x4f, 0xfb,
	0xe7, 0xdd, 0xbd, 0xde, 0xb7, 0xbd, 0xee, 0xbe, 0xfe, 0x41, 0x0c, 0x1c, 0xb4, 0x87, 0x07, 0xdd,
	0x51, 0xef, 0x74, 0xf0, 0x72, 0x57, 0xd7, 0x90, 0x0e, 0x2b, 0x0a, 0xd8, 0x3f, 0x1b, 0x76, 0x8e,
	0xbb, 0x7a, 0x09, 0xad, 0x41, 0x5d, 0x21, 0x87, 0xbd, 0xfe, 0xe0, 0xec, 0x00, 0xb7, 0x4f, 0xf4,
	0x32, 0x6a, 0xc0, 0x87, 0x7b, 0x67, 0xc3, 0xd3, 0x41, 0x17, 0x27, 0xca, 0x0a, 0x42, 0xb0, 0x9a,
	0x42, 0x89, 0x76, 0x01, 0x19, 0xb0, 0xbe, 0x37, 0x3c, 0x19, 0x1e, 0xb7, 0x07, 0xbd, 0x8b, 0xbc,
	0x41, 0x15, 0xd5, 0x60, 0xb1, 0x3f, 0x3c, 0x39, 0x69, 0xe3, 0x4b, 0x7d, 0xd1, 0xfc, 0x5e, 0x83,
	0xfa, 0x5c, 0xb9, 0xa1, 0x2f, 0x61, 0x45, 0x1d, 0xe9, 0x35, 0x71, 0x22, 0xca, 0x0d, 0x4d, 0x5e,
	0x9a, 0x51, 0xcc, 0xc9, 0x71, 0xcc, 0xb8, 0x88, 0x09, 0xb8, 0xe6, 0xcc, 0xc6, 0x1c, 0xbd, 0x80,
	0x6a, 0xe0, 0x33, 0x4f, 0xa4, 0xfd, 0x69, 0xdc, 0x53, 0xda, 0x4a, 0x96, 0xf0, 0xcc, 0x1f, 0x35,
	0xd0, 0xe7, 0xcb, 0xf4, 0x61, 0x31, 0xec, 0xcc, 0xc5, 0xb0, 0x71, 0x5f, 0x4f, 0x14, 0x83, 0xf8,
	0xb9, 0x04, 0x6b, 0xf7, 0xd4, 0xf6, 0xc3, 0xe2, 0xd8, 0x9d, 0x8b, 0xe3, 0xf1, 0x1b, 0x7a, 0xa9,
	0x10, 0x0a, 0xba, 0x84, 0x3a, 0xbd, 0x0d, 0x1c, 0x66, 0x33, 0x31, 0x1a, 0xfb, 0x91, 0x37, 0xe1,
	0xb2, 0x52, 0x6b, 0xad, 0x17, 0xff, 0xda, 0x8a, 0x56, 0x37, 0x11, 0x76, 0xa4, 0x0e, 0xaf, 0xd2,
	0xc2, 0xbc, 0xb9, 0x0d, 0xab, 0x45, 0x06, 0x7a, 0x04, 0xd5, 0x64, 0x8f, 0xf8, 0x64, 0x1a, 0x4e,
	0x66, 0xe6, 0x4f, 0x1a, 0x34, 0xee, 0xf4, 0xe5, 0xc3, 0xb2, 0xd1, 0x9a, 0xcb, 0x46, 0xf3, 0xde,
	0x57, 0xa0, 0x78, 0x2d, 0xdf, 0x00, 0x64, 0x76, 0x68, 0x1d, 0x16, 0xe4, 0xc6, 0x49, 0xbf, 0xab,
	0x09, 0xfa, 0x08, 0x96, 0xaf, 0x09, 0x57, 0x21, 0xc9, 0x76, 0x5f, 0xc2, 0x4b, 0xd7, 0x84, 0x4b,
	0x89, 0xf9, 0x83, 0x06, 0x90, 0xd5, 0x1c, 0xb2, 0x60, 0x8d, 0x0b, 0x12, 0x0a, 0xf9, 0x26, 0x8d,
	0x22, 0x8f, 0xdd, 0x7a, 0xc4, 0xf3, 0xa5, 0x9f, 0x8e, 0x1b, 0x72, 0x29, 0x3e, 0xee, 0x30, 0x59,
	0x40, 0x9f, 0x02, 0x92, 0xaf, 0x97, 0x20, 0x6e, 0x90, 0xd1, 0x4b, 0x8a, 0x3e, 0x5b, 0x99, 0xd1,
	0x67, 0x01, 0xc6, 0x17, 0x56, 0x4e, 0x02, 0x8c, 0x0b, 0xbc, 0x96, 0xab, 0xb9, 0xf7, 0x1a, 0x84,
	0x96, 0x06, 0xf1, 0x47, 0x19, 0x56, 0x8b, 0x05, 0xf7, 0x1e, 0xe2, 0xb0, 0xfd, 0xc8, 0x13, 0x69,
	0x32, 0xe4, 0x04, 0xe9, 0x50, 0xe6, 0x91, 0x2b, 0xdf, 0x59, 0x0d, 0xc7, 0x43, 0xf4, 0x35, 0x2c,
	0x8e, 0x23, 0xfb, 0x86, 0x8a, 0xf4, 0x2f, 0xe7, 0xe9, 0xdb, 0xda, 0xc4, 0xea, 0x48, 0x2e, 0x4e,
	0x35, 0xcd, 0xbf, 0x35, 0xa8, 0x2a, 0x2c, 0xdb, 0x51, 0xcb, 0xef, 0x78, 0x08, 0x4b, 0xf4, 0x96,
	0xba, 0x81, 0x43, 0xc2, 0xe4, 0xaf, 0xfa, 0xd9, 0x3b, 0x6c, 0x60, 0x75, 0x13, 0x0d, 0x9e, 0xa9,
	0x9b, 0xbf, 0x68, 0xb0, 0x94, 0xc2, 0xc5, 0x62, 0x4c, 0xd3, 0xfc, 0x5f, 0x73, 0xd4, 0x81, 0x1a,
	0x11, 0x82, 0xd8, 0xd7, 0x71, 0x28, 0xe9, 0xd7, 0xc0, 0xd6, 0x5c, 0x63, 0x88, 0x90, 0x79, 0x57,
	0x47, 0x54, 0xb5, 0xc6, 0x39, 0x61, 0x21, 0xce, 0x8b, 0xcc, 0xaf, 0x00, 0xdd, 0xa5, 0xc4, 0x79,
	0xbe, 0xa1, 0xd3, 0xa4, 0x53, 0xe2, 0x61, 0x16, 0x70, 0x29, 0xd7, 0x3d, 0xe6, 0x5f, 0x25, 0x58,
	0xc9, 0xb7, 0xde, 0xff, 0xa5, 0x2a, 0xbe, 0x80, 0x0d, 0xb9, 0x34, 0x22, 0xde, 0x64, 0xc4, 0x23,
	0x77, 0x14, 0x79, 0x3c, 0xa0, 0x36, 0x7b, 0xc5, 0xe8, 0xc4, 0x58, 0x90, 0x5d, 0xfe, 0x48, 0x12,
	0xda, 0xde, 0xa4, 0x1f, 0xb9, 0xc3, 0x6c, 0x15, 0x5d, 0x42, 0x23, 0xa0, 0xa1, 0x4d, 0x3d, 0xc1,
	0x1c, 0x9a, 0x3e, 0x55, 0xea, 0xcb, 0xe3, 0xd9, 0x9b, 0xdf, 0x1c, 0x4b, 0xfe, 0xb6, 0xc5, 0xf9,
	0x4c, 0x8a, 0xf5, 0xcc, 0x46, 0xbd, 0x61, 0xcd, 0x1e, 0x34, 0xee, 0xd0, 0xd0, 0x26, 0x40, 0x46,
	0x4c, 0xca, 0x21, 0x87, 0x14, 0x13, 0x9f, 0x56, 0x4a, 0xe7, 0x10, 0x1e, 0x33, 0xdf, 0xf2, 0x03,
	0xea, 0xd9, 0xd4, 0xe3, 0x51, 0xf2, 0x9d, 0x6c, 0x89, 0x90, 0xd8, 0xd4, 0x7a, 0xbd, 0xd3, 0x81,
	0x41, 0x3c, 0x3a, 0x8f, 0xc1, 0x73, 0xed, 0xcf, 0xd2, 0xc6, 0x59, 0x40, 0xbd, 0x3d, 0xc5, 0x94,
	0xa0, 0x25, 0xd7, 0xad, 0x8b, 0x9d, 0x71, 0x55, 0x2a, 0x3f, 0xfb, 0x27, 0x00, 0x00, 0xff, 0xff,
	0xba, 0xb8, 0xfe, 0x4c, 0xba, 0x0b, 0x00, 0x00,
}
