apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: omnition
    component: otpexp-server-${PROTOCOL}
  name: otpexp-server-${PROTOCOL}
  namespace: ${K8S_NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: otpexp-server-${PROTOCOL}
  template:
    metadata:
      labels:
        component: otpexp-server-${PROTOCOL}
      annotations:
        prometheus.io/path: "/metrics"
        prometheus.io/scrape: "true"
        version: "${VERSION}"
        restart: "1"
    spec:
      containers:
      - image: crccheck/hello-world:latest
        imagePullPolicy: Always
        name: hello-world
        ports:
          - containerPort: 8000
            name: main 
      - image: 592865182265.dkr.ecr.us-west-2.amazonaws.com/otpexp-server:latest
        imagePullPolicy: Always
        name: otpexp-server-${PROTOCOL}
        args: ["/app/server", "-protocol", "${PROTOCOL}", "-listen", "0.0.0.0:3465"]
        ports:
          - containerPort: 3465
            name: main 
          - containerPort: 2112
            name: metrics

